### ISSUE TITLE
UUID not needed anymore

### ISSUE THREAD

**Issue by j1nx** [MycroftAI/skill-pairing#53]
This skill pip installs the uuid package/library, but is already included within Python >2.5

**Comment by forslund** [comment]
So it has basically never been necessary? Good catch. :)

**Comment by j1nx** [comment]
Yes, I discoverd that UUID could be deleted while looking at the Typing requirement last time. I was puzzled that after a clean install it was there again?

Some linux grep magic showed this skill installed it again.

Not sure though if the import needs to be adjusted;
https://github.com/MycroftAI/skill-pairing/blob/19.08/__init__.py#L17

But you are the Python wizard :)

**Comment by forslund** [comment]
Just tested to remove the dependency and pairing still works so it can be removed without issues it seems.
